# Generated by Django 4.1.3 on 2023-03-13 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_banner',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
