# Generated by Django 4.1.3 on 2023-03-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_is_banner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other_forms',
            new_name='Forma',
        ),
        migrations.AddField(
            model_name='shop',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Team_jersey',
        ),
    ]
