# Generated by Django 4.1.3 on 2023-03-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_other_forms_forma_shop_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Acsdemiy/')),
                ('text', models.TextField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
